name: Daily Bot Run
on:
  schedule:
    - cron: '24 17 * * *' # Runs every day at 17:24 UTC
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ATTENDANCE_CHANNEL_ID: ${{ secrets.ATTENDANCE_CHANNEL_ID }}
          COMMITTEE_ROLE_ID: ${{ secrets.COMMITTEE_ROLE_ID }}
        run: |
          python src/bot.py
