name: Test Workflow Template
on:
  workflow_dispatch:
jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder Step
        run: echo "This is a placeholder workflow template"
